-- Generated by Oracle SQL Developer Data Modeler 24.3.1.347.1153
--   at:        2026-07-19 03:12:46 BDT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE USER medicore IDENTIFIED BY account

unlock;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE medicore.appointment (
    appointment_id   NUMBER NOT NULL,
    patient_id       NUMBER NOT NULL,
    doctor_id        NUMBER NOT NULL,
    appointment_date DATE NOT NULL,
    appointment_time VARCHAR2(10 BYTE) NOT NULL,
    booking_date     DATE DEFAULT sysdate,
    status           VARCHAR2(20 BYTE) DEFAULT 'Pending',
    queue_number     NUMBER DEFAULT 0
)
TABLESPACE system
LOGGING;

ALTER TABLE medicore.appointment
    ADD CONSTRAINT appointment_pk PRIMARY KEY ( appointment_id )
        USING INDEX TABLESPACE system
LOGGING;

CREATE TABLE medicore.bill (
    bill_id      NUMBER NOT NULL,
    patient_id   NUMBER NOT NULL,
    bill_date    DATE DEFAULT sysdate,
    total_amount NUMBER(10, 2) DEFAULT 0,
    discount     NUMBER(10, 2) DEFAULT 0,
    net_amount   NUMBER(10, 2) DEFAULT 0,
    status       VARCHAR2(20 BYTE) DEFAULT 'Unpaid'
)
TABLESPACE system
LOGGING;

ALTER TABLE medicore.bill
    ADD CONSTRAINT bill_pk PRIMARY KEY ( bill_id )
        USING INDEX TABLESPACE system
LOGGING;

CREATE TABLE medicore.department (
    department_id   NUMBER NOT NULL,
    department_name VARCHAR2(100 BYTE) NOT NULL,
    department_head VARCHAR2(100 BYTE)
)
TABLESPACE system
LOGGING;

ALTER TABLE medicore.department
    ADD CONSTRAINT department_pk PRIMARY KEY ( department_id )
        USING INDEX TABLESPACE system
LOGGING;

ALTER TABLE medicore.department
    ADD CONSTRAINT department_department_name_un UNIQUE ( department_name )
        USING INDEX TABLESPACE system
LOGGING;

CREATE TABLE medicore.doctor (
    doctor_id        NUMBER NOT NULL,
    department_id    NUMBER,
    name             VARCHAR2(100 BYTE) NOT NULL,
    gender           VARCHAR2(10 BYTE),
    date_of_birth    DATE,
    specialization   VARCHAR2(100 BYTE),
    qualification    VARCHAR2(100 BYTE),
    phone            VARCHAR2(20 BYTE) NOT NULL,
    email            VARCHAR2(100 BYTE) NOT NULL,
    consultation_fee NUMBER(10, 2) NOT NULL,
    joining_date     DATE DEFAULT sysdate,
    status           VARCHAR2(20 BYTE) DEFAULT 'Active'
)
TABLESPACE system
LOGGING;

ALTER TABLE medicore.doctor
    ADD CONSTRAINT doctor_pk PRIMARY KEY ( doctor_id )
        USING INDEX TABLESPACE system
LOGGING;

ALTER TABLE medicore.doctor
    ADD CONSTRAINT doctor_phone_un UNIQUE ( phone )
        USING INDEX TABLESPACE system
LOGGING;

ALTER TABLE medicore.doctor
    ADD CONSTRAINT doctor_email_un UNIQUE ( email )
        USING INDEX TABLESPACE system
LOGGING;

CREATE TABLE medicore.emergency_queue (
    queue_id       NUMBER NOT NULL,
    patient_id     NUMBER NOT NULL,
    arrival_time   DATE DEFAULT sysdate,
    priority_level NUMBER NOT NULL,
    status         VARCHAR2(20 BYTE) DEFAULT 'Waiting'
)
TABLESPACE system
LOGGING;

ALTER TABLE medicore.emergency_queue
    ADD CONSTRAINT emergency_queue_pk PRIMARY KEY ( queue_id )
        USING INDEX TABLESPACE system
LOGGING;

CREATE TABLE medicore.financial_ledger (
    ledger_id        NUMBER NOT NULL,
    transaction_type VARCHAR2(50 BYTE) NOT NULL,
    reference_id     NUMBER NOT NULL,
    patient_id       NUMBER NOT NULL,
    doctor_id        NUMBER,
    total_amount     NUMBER(10, 2) NOT NULL,
    doctor_amount    NUMBER(10, 2) NOT NULL,
    admin_amount     NUMBER(10, 2) NOT NULL,
    transaction_date DATE DEFAULT sysdate,
    is_cleared       VARCHAR2(1 BYTE) DEFAULT 'N'
)
TABLESPACE system
LOGGING;

CREATE UNIQUE INDEX medicore.financial_ledger_pk ON
    medicore.financial_ledger (
        ledger_id
    ASC )
        TABLESPACE system LOGGING;

ALTER TABLE medicore.financial_ledger
    ADD CONSTRAINT financial_ledger_pk PRIMARY KEY ( ledger_id )
        USING INDEX medicore.financial_ledger_pk;

CREATE TABLE medicore.lab_test (
    test_id     NUMBER NOT NULL,
    test_name   VARCHAR2(100 BYTE) NOT NULL,
    description VARCHAR2(255 BYTE),
    test_fee    NUMBER(10, 2) NOT NULL,
    status      VARCHAR2(20 BYTE) DEFAULT 'Available'
)
TABLESPACE system
LOGGING;

ALTER TABLE medicore.lab_test
    ADD CONSTRAINT lab_test_pk PRIMARY KEY ( test_id )
        USING INDEX TABLESPACE system
LOGGING;

CREATE TABLE medicore.lab_test_record (
    record_id        NUMBER NOT NULL,
    patient_id       NUMBER NOT NULL,
    doctor_id        NUMBER NOT NULL,
    test_id          NUMBER NOT NULL,
    order_date       DATE DEFAULT sysdate,
    result_details   CLOB,
    report_date      DATE,
    status           VARCHAR2(20 BYTE) DEFAULT 'Pending',
    waive_commission VARCHAR2(1 BYTE) DEFAULT 'N',
    payment_status   VARCHAR2(20 BYTE) DEFAULT 'Unpaid'
)
TABLESPACE system
LOGGING
    LOB ( result_details ) STORE AS (
        TABLESPACE system
        STORAGE ( PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 BUFFER_POOL DEFAULT )
        CHUNK 8192
        RETENTION
        ENABLE STORAGE IN ROW
        NOCACHE LOGGING
    );

ALTER TABLE medicore.lab_test_record
    ADD CONSTRAINT lab_test_record_pk PRIMARY KEY ( record_id )
        USING INDEX TABLESPACE system
LOGGING;

CREATE TABLE medicore.medicine_store (
    medicine_id    NUMBER NOT NULL,
    medicine_name  VARCHAR2(100 BYTE) NOT NULL,
    generic_name   VARCHAR2(100 BYTE),
    manufacturer   VARCHAR2(100 BYTE),
    unit_price     NUMBER(10, 2) NOT NULL,
    stock_quantity NUMBER DEFAULT 0,
    status         VARCHAR2(20 BYTE) DEFAULT 'Available'
)
TABLESPACE system
LOGGING;

ALTER TABLE medicore.medicine_store
    ADD CONSTRAINT medicine_store_pk PRIMARY KEY ( medicine_id )
        USING INDEX TABLESPACE system
LOGGING;

CREATE TABLE medicore.patient (
    patient_id        NUMBER NOT NULL,
    name              VARCHAR2(100 BYTE) NOT NULL,
    gender            VARCHAR2(10 BYTE),
    date_of_birth     DATE,
    blood_group       VARCHAR2(5 BYTE),
    phone             VARCHAR2(20 BYTE) NOT NULL,
    email             VARCHAR2(100 BYTE),
    address           VARCHAR2(255 BYTE),
    emergency_contact VARCHAR2(20 BYTE),
    registration_date DATE DEFAULT sysdate,
    status            VARCHAR2(20 BYTE) DEFAULT 'Active'
)
TABLESPACE system
LOGGING;

ALTER TABLE medicore.patient
    ADD CONSTRAINT patient_pk PRIMARY KEY ( patient_id )
        USING INDEX TABLESPACE system
LOGGING;

ALTER TABLE medicore.patient
    ADD CONSTRAINT patient_phone_un UNIQUE ( phone )
        USING INDEX TABLESPACE system
LOGGING;

CREATE TABLE medicore.prescription (
    prescription_id   NUMBER NOT NULL,
    appointment_id    NUMBER NOT NULL,
    patient_id        NUMBER NOT NULL,
    doctor_id         NUMBER NOT NULL,
    prescription_date DATE DEFAULT sysdate,
    diagnosis         VARCHAR2(255 BYTE),
    medicines         CLOB,
    notes             CLOB
)
TABLESPACE system
LOGGING
        LOB ( medicines ) STORE AS (
            TABLESPACE system
            STORAGE ( PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 BUFFER_POOL DEFAULT )
            CHUNK 8192
            RETENTION
            ENABLE STORAGE IN ROW
            NOCACHE LOGGING
        )
        LOB ( notes ) STORE AS (
            TABLESPACE system
            STORAGE ( PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 BUFFER_POOL DEFAULT )
            CHUNK 8192
            RETENTION
            ENABLE STORAGE IN ROW
            NOCACHE LOGGING
        );

ALTER TABLE medicore.prescription
    ADD CONSTRAINT prescription_pk PRIMARY KEY ( prescription_id )
        USING INDEX TABLESPACE system
LOGGING;

CREATE TABLE medicore.user_account (
    user_id       NUMBER NOT NULL,
    doctor_id     NUMBER,
    username      VARCHAR2(50 BYTE) NOT NULL,
    password_hash VARCHAR2(255 BYTE) NOT NULL,
    role          VARCHAR2(20 BYTE) NOT NULL,
    status        VARCHAR2(20 BYTE) DEFAULT 'Active',
    created_date  DATE DEFAULT sysdate,
    patient_id    NUMBER
)
TABLESPACE system
LOGGING;

ALTER TABLE medicore.user_account
    ADD CONSTRAINT user_account_pk PRIMARY KEY ( user_id )
        USING INDEX TABLESPACE system
LOGGING;

ALTER TABLE medicore.user_account
    ADD CONSTRAINT user_account_username_un UNIQUE ( username )
        USING INDEX TABLESPACE system
LOGGING;

ALTER TABLE medicore.appointment
    ADD CONSTRAINT fk_apt_doc
        FOREIGN KEY ( doctor_id )
            REFERENCES medicore.doctor ( doctor_id )
            NOT DEFERRABLE;

ALTER TABLE medicore.appointment
    ADD CONSTRAINT fk_apt_pat
        FOREIGN KEY ( patient_id )
            REFERENCES medicore.patient ( patient_id )
            NOT DEFERRABLE;

ALTER TABLE medicore.bill
    ADD CONSTRAINT fk_bil_pat
        FOREIGN KEY ( patient_id )
            REFERENCES medicore.patient ( patient_id )
            NOT DEFERRABLE;

ALTER TABLE medicore.doctor
    ADD CONSTRAINT fk_doc_dept
        FOREIGN KEY ( department_id )
            REFERENCES medicore.department ( department_id )
            NOT DEFERRABLE;

ALTER TABLE medicore.emergency_queue
    ADD CONSTRAINT fk_emq_pat
        FOREIGN KEY ( patient_id )
            REFERENCES medicore.patient ( patient_id )
            NOT DEFERRABLE;

ALTER TABLE medicore.financial_ledger
    ADD CONSTRAINT fk_ledger_doc
        FOREIGN KEY ( doctor_id )
            REFERENCES medicore.doctor ( doctor_id )
                ON DELETE SET NULL
            NOT DEFERRABLE;

ALTER TABLE medicore.financial_ledger
    ADD CONSTRAINT fk_ledger_pat
        FOREIGN KEY ( patient_id )
            REFERENCES medicore.patient ( patient_id )
            NOT DEFERRABLE;

ALTER TABLE medicore.lab_test_record
    ADD CONSTRAINT fk_ltr_doc
        FOREIGN KEY ( doctor_id )
            REFERENCES medicore.doctor ( doctor_id )
            NOT DEFERRABLE;

ALTER TABLE medicore.lab_test_record
    ADD CONSTRAINT fk_ltr_pat
        FOREIGN KEY ( patient_id )
            REFERENCES medicore.patient ( patient_id )
            NOT DEFERRABLE;

ALTER TABLE medicore.lab_test_record
    ADD CONSTRAINT fk_ltr_tst
        FOREIGN KEY ( test_id )
            REFERENCES medicore.lab_test ( test_id )
            NOT DEFERRABLE;

ALTER TABLE medicore.prescription
    ADD CONSTRAINT fk_prs_apt
        FOREIGN KEY ( appointment_id )
            REFERENCES medicore.appointment ( appointment_id )
            NOT DEFERRABLE;

ALTER TABLE medicore.prescription
    ADD CONSTRAINT fk_prs_doc
        FOREIGN KEY ( doctor_id )
            REFERENCES medicore.doctor ( doctor_id )
            NOT DEFERRABLE;

ALTER TABLE medicore.prescription
    ADD CONSTRAINT fk_prs_pat
        FOREIGN KEY ( patient_id )
            REFERENCES medicore.patient ( patient_id )
            NOT DEFERRABLE;

ALTER TABLE medicore.user_account
    ADD CONSTRAINT fk_usr_doc
        FOREIGN KEY ( doctor_id )
            REFERENCES medicore.doctor ( doctor_id )
                ON DELETE SET NULL
            NOT DEFERRABLE;

ALTER TABLE medicore.user_account
    ADD CONSTRAINT fk_usr_pat
        FOREIGN KEY ( patient_id )
            REFERENCES medicore.patient ( patient_id )
                ON DELETE SET NULL
            NOT DEFERRABLE;

CREATE SEQUENCE medicore.apt_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER medicore.trg_apt_id BEFORE
    INSERT ON medicore.appointment
    FOR EACH ROW
    WHEN ( new.appointment_id IS NULL )
BEGIN
    :new.appointment_id := medicore.apt_seq.nextval;
END;
/

CREATE SEQUENCE medicore.bil_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER medicore.trg_bil_id BEFORE
    INSERT ON medicore.bill
    FOR EACH ROW
    WHEN ( new.bill_id IS NULL )
BEGIN
    :new.bill_id := medicore.bil_seq.nextval;
END;
/

CREATE SEQUENCE medicore.dept_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER medicore.trg_dept_id BEFORE
    INSERT ON medicore.department
    FOR EACH ROW
    WHEN ( new.department_id IS NULL )
BEGIN
    :new.department_id := medicore.dept_seq.nextval;
END;
/

CREATE SEQUENCE medicore.doc_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER medicore.trg_doc_id BEFORE
    INSERT ON medicore.doctor
    FOR EACH ROW
    WHEN ( new.doctor_id IS NULL )
BEGIN
    :new.doctor_id := medicore.doc_seq.nextval;
END;
/

CREATE SEQUENCE medicore.emq_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER medicore.trg_emq_id BEFORE
    INSERT ON medicore.emergency_queue
    FOR EACH ROW
    WHEN ( new.queue_id IS NULL )
BEGIN
    :new.queue_id := medicore.emq_seq.nextval;
END;
/

CREATE SEQUENCE medicore.ledger_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER medicore.trg_ledger_id BEFORE
    INSERT ON medicore.financial_ledger
    FOR EACH ROW
    WHEN ( new.ledger_id IS NULL )
BEGIN
    :new.ledger_id := medicore.ledger_seq.nextval;
END;
/

CREATE SEQUENCE medicore.lab_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER medicore.trg_lab_id BEFORE
    INSERT ON medicore.lab_test
    FOR EACH ROW
    WHEN ( new.test_id IS NULL )
BEGIN
    :new.test_id := medicore.lab_seq.nextval;
END;
/

CREATE SEQUENCE medicore.ltr_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER medicore.trg_ltr_id BEFORE
    INSERT ON medicore.lab_test_record
    FOR EACH ROW
    WHEN ( new.record_id IS NULL )
BEGIN
    :new.record_id := medicore.ltr_seq.nextval;
END;
/

CREATE SEQUENCE medicore.med_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER medicore.trg_med_id BEFORE
    INSERT ON medicore.medicine_store
    FOR EACH ROW
    WHEN ( new.medicine_id IS NULL )
BEGIN
    :new.medicine_id := medicore.med_seq.nextval;
END;
/

CREATE SEQUENCE medicore.pat_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER medicore.trg_pat_id BEFORE
    INSERT ON medicore.patient
    FOR EACH ROW
    WHEN ( new.patient_id IS NULL )
BEGIN
    :new.patient_id := medicore.pat_seq.nextval;
END;
/

CREATE SEQUENCE medicore.prs_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER medicore.trg_prs_id BEFORE
    INSERT ON medicore.prescription
    FOR EACH ROW
    WHEN ( new.prescription_id IS NULL )
BEGIN
    :new.prescription_id := medicore.prs_seq.nextval;
END;
/

CREATE SEQUENCE medicore.usr_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER medicore.trg_usr_id BEFORE
    INSERT ON medicore.user_account
    FOR EACH ROW
    WHEN ( new.user_id IS NULL )
BEGIN
    :new.user_id := medicore.usr_seq.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            12
-- CREATE INDEX                             1
-- ALTER TABLE                             32
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                          12
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                         12
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              1
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
