

CREATE TABLE DEPARTMENT (
    Department_ID NUMBER PRIMARY KEY,
    Department_Name VARCHAR2(100) UNIQUE NOT NULL,
    Department_Head VARCHAR2(100)
);

CREATE TABLE DOCTOR (
    Doctor_ID NUMBER PRIMARY KEY,
    Department_ID NUMBER,
    Name VARCHAR2(100) NOT NULL,
    Gender VARCHAR2(10),
    Date_Of_Birth DATE,
    Specialization VARCHAR2(100),
    Qualification VARCHAR2(100),
    Phone VARCHAR2(20) UNIQUE NOT NULL,
    Email VARCHAR2(100) UNIQUE NOT NULL,
    Consultation_Fee NUMBER(10,2) NOT NULL,
    Joining_Date DATE DEFAULT SYSDATE,
    Status VARCHAR2(20) DEFAULT 'Active',
    CONSTRAINT fk_doc_dept FOREIGN KEY (Department_ID) REFERENCES DEPARTMENT(Department_ID)
);

CREATE TABLE USER_ACCOUNT (
    User_ID NUMBER PRIMARY KEY,
    Doctor_ID NUMBER NULL,
    Patient_ID NUMBER NULL,
    Username VARCHAR2(50) UNIQUE NOT NULL,
    Password_Hash VARCHAR2(255) NOT NULL,
    Role VARCHAR2(20) NOT NULL,
    Status VARCHAR2(20) DEFAULT 'Active',
    Created_Date DATE DEFAULT SYSDATE,
    CONSTRAINT fk_usr_doc FOREIGN KEY (Doctor_ID) REFERENCES DOCTOR(Doctor_ID) ON DELETE SET NULL,
    CONSTRAINT fk_usr_pat FOREIGN KEY (Patient_ID) REFERENCES PATIENT(Patient_ID) ON DELETE SET NULL
);

CREATE TABLE PATIENT (
    Patient_ID NUMBER PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Gender VARCHAR2(10),
    Date_Of_Birth DATE,
    Blood_Group VARCHAR2(5),
    Phone VARCHAR2(20) UNIQUE NOT NULL,
    Email VARCHAR2(100),
    Address VARCHAR2(255),
    Emergency_Contact VARCHAR2(20),
    Registration_Date DATE DEFAULT SYSDATE,
    Status VARCHAR2(20) DEFAULT 'Active'
);

CREATE TABLE APPOINTMENT (
    Appointment_ID NUMBER PRIMARY KEY,
    Patient_ID NUMBER NOT NULL,
    Doctor_ID NUMBER NOT NULL,
    Appointment_Date DATE NOT NULL,
    Appointment_Time VARCHAR2(10) NOT NULL,
    Booking_Date DATE DEFAULT SYSDATE,
    Status VARCHAR2(20) DEFAULT 'Pending',
    CONSTRAINT fk_apt_pat FOREIGN KEY (Patient_ID) REFERENCES PATIENT(Patient_ID),
    CONSTRAINT fk_apt_doc FOREIGN KEY (Doctor_ID) REFERENCES DOCTOR(Doctor_ID)
);

CREATE TABLE PRESCRIPTION (
    Prescription_ID NUMBER PRIMARY KEY,
    Appointment_ID NUMBER NOT NULL,
    Patient_ID NUMBER NOT NULL,
    Doctor_ID NUMBER NOT NULL,
    Prescription_Date DATE DEFAULT SYSDATE,
    Diagnosis VARCHAR2(255),
    Medicines CLOB,
    Notes CLOB,
    CONSTRAINT fk_prs_apt FOREIGN KEY (Appointment_ID) REFERENCES APPOINTMENT(Appointment_ID),
    CONSTRAINT fk_prs_pat FOREIGN KEY (Patient_ID) REFERENCES PATIENT(Patient_ID),
    CONSTRAINT fk_prs_doc FOREIGN KEY (Doctor_ID) REFERENCES DOCTOR(Doctor_ID)
);

CREATE TABLE LAB_TEST (
    Test_ID NUMBER PRIMARY KEY,
    Test_Name VARCHAR2(100) NOT NULL,
    Description VARCHAR2(255),
    Test_Fee NUMBER(10,2) NOT NULL,
    Status VARCHAR2(20) DEFAULT 'Available'
);

CREATE TABLE LAB_TEST_RECORD (
    Record_ID NUMBER PRIMARY KEY,
    Patient_ID NUMBER NOT NULL,
    Doctor_ID NUMBER NOT NULL,
    Test_ID NUMBER NOT NULL,
    Order_Date DATE DEFAULT SYSDATE,
    Result_Details CLOB,
    Report_Date DATE,
    Status VARCHAR2(20) DEFAULT 'Pending',
    CONSTRAINT fk_ltr_pat FOREIGN KEY (Patient_ID) REFERENCES PATIENT(Patient_ID),
    CONSTRAINT fk_ltr_doc FOREIGN KEY (Doctor_ID) REFERENCES DOCTOR(Doctor_ID),
    CONSTRAINT fk_ltr_tst FOREIGN KEY (Test_ID) REFERENCES LAB_TEST(Test_ID)
);

CREATE TABLE ROOM (
    Room_ID NUMBER PRIMARY KEY,
    Room_Number VARCHAR2(20) UNIQUE NOT NULL,
    Room_Type VARCHAR2(50) NOT NULL,
    Daily_Charge NUMBER(10,2) NOT NULL,
    Status VARCHAR2(20) DEFAULT 'Available'
);

CREATE TABLE BED (
    Bed_ID NUMBER PRIMARY KEY,
    Room_ID NUMBER NOT NULL,
    Bed_Number VARCHAR2(20) NOT NULL,
    Status VARCHAR2(20) DEFAULT 'Available',
    CONSTRAINT fk_bed_rm FOREIGN KEY (Room_ID) REFERENCES ROOM(Room_ID)
);

CREATE TABLE ADMISSION (
    Admission_ID NUMBER PRIMARY KEY,
    Patient_ID NUMBER NOT NULL,
    Room_ID NUMBER NOT NULL,
    Bed_ID NUMBER NOT NULL,
    Admission_Date DATE DEFAULT SYSDATE,
    Discharge_Date DATE,
    Status VARCHAR2(20) DEFAULT 'Admitted',
    CONSTRAINT fk_adm_pat FOREIGN KEY (Patient_ID) REFERENCES PATIENT(Patient_ID),
    CONSTRAINT fk_adm_rm FOREIGN KEY (Room_ID) REFERENCES ROOM(Room_ID),
    CONSTRAINT fk_adm_bed FOREIGN KEY (Bed_ID) REFERENCES BED(Bed_ID)
);

CREATE TABLE EMERGENCY_QUEUE (
    Queue_ID NUMBER PRIMARY KEY,
    Patient_ID NUMBER NOT NULL,
    Arrival_Time DATE DEFAULT SYSDATE,
    Priority_Level NUMBER NOT NULL, -- 1: Critical, 2: Urgent, 3: Stable
    Status VARCHAR2(20) DEFAULT 'Waiting',
    CONSTRAINT fk_emq_pat FOREIGN KEY (Patient_ID) REFERENCES PATIENT(Patient_ID)
);

CREATE TABLE MEDICINE_STORE (
    Medicine_ID NUMBER PRIMARY KEY,
    Medicine_Name VARCHAR2(100) NOT NULL,
    Generic_Name VARCHAR2(100),
    Manufacturer VARCHAR2(100),
    Unit_Price NUMBER(10,2) NOT NULL,
    Stock_Quantity NUMBER DEFAULT 0,
    Status VARCHAR2(20) DEFAULT 'Available'
);

CREATE TABLE BILL (
    Bill_ID NUMBER PRIMARY KEY,
    Patient_ID NUMBER NOT NULL,
    Bill_Date DATE DEFAULT SYSDATE,
    Total_Amount NUMBER(10,2) DEFAULT 0,
    Discount NUMBER(10,2) DEFAULT 0,
    Net_Amount NUMBER(10,2) DEFAULT 0,
    Status VARCHAR2(20) DEFAULT 'Unpaid',
    CONSTRAINT fk_bil_pat FOREIGN KEY (Patient_ID) REFERENCES PATIENT(Patient_ID)
);

CREATE TABLE PAYMENT (
    Payment_ID NUMBER PRIMARY KEY,
    Bill_ID NUMBER NOT NULL,
    Payment_Date DATE DEFAULT SYSDATE,
    Amount NUMBER(10,2) NOT NULL,
    Payment_Method VARCHAR2(50),
    Payment_Status VARCHAR2(20) DEFAULT 'Completed',
    Transaction_ID VARCHAR2(100) UNIQUE,
    CONSTRAINT fk_pay_bil FOREIGN KEY (Bill_ID) REFERENCES BILL(Bill_ID)
);

-- Sequences and Triggers for Auto-Increment (Oracle 11g compatibility)

CREATE SEQUENCE dept_seq START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER trg_dept_id
BEFORE INSERT ON DEPARTMENT
FOR EACH ROW
BEGIN
    IF :NEW.Department_ID IS NULL THEN
        SELECT dept_seq.NEXTVAL INTO :NEW.Department_ID FROM DUAL;
    END IF;
END;
/

CREATE SEQUENCE doc_seq START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER trg_doc_id
BEFORE INSERT ON DOCTOR
FOR EACH ROW
BEGIN
    IF :NEW.Doctor_ID IS NULL THEN
        SELECT doc_seq.NEXTVAL INTO :NEW.Doctor_ID FROM DUAL;
    END IF;
END;
/

CREATE SEQUENCE usr_seq START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER trg_usr_id
BEFORE INSERT ON USER_ACCOUNT
FOR EACH ROW
BEGIN
    IF :NEW.User_ID IS NULL THEN
        SELECT usr_seq.NEXTVAL INTO :NEW.User_ID FROM DUAL;
    END IF;
END;
/

CREATE SEQUENCE pat_seq START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER trg_pat_id
BEFORE INSERT ON PATIENT
FOR EACH ROW
BEGIN
    IF :NEW.Patient_ID IS NULL THEN
        SELECT pat_seq.NEXTVAL INTO :NEW.Patient_ID FROM DUAL;
    END IF;
END;
/

CREATE SEQUENCE apt_seq START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER trg_apt_id
BEFORE INSERT ON APPOINTMENT
FOR EACH ROW
BEGIN
    IF :NEW.Appointment_ID IS NULL THEN
        SELECT apt_seq.NEXTVAL INTO :NEW.Appointment_ID FROM DUAL;
    END IF;
END;
/

CREATE SEQUENCE prs_seq START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER trg_prs_id
BEFORE INSERT ON PRESCRIPTION
FOR EACH ROW
BEGIN
    IF :NEW.Prescription_ID IS NULL THEN
        SELECT prs_seq.NEXTVAL INTO :NEW.Prescription_ID FROM DUAL;
    END IF;
END;
/

CREATE SEQUENCE lab_seq START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER trg_lab_id
BEFORE INSERT ON LAB_TEST
FOR EACH ROW
BEGIN
    IF :NEW.Test_ID IS NULL THEN
        SELECT lab_seq.NEXTVAL INTO :NEW.Test_ID FROM DUAL;
    END IF;
END;
/

CREATE SEQUENCE ltr_seq START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER trg_ltr_id
BEFORE INSERT ON LAB_TEST_RECORD
FOR EACH ROW
BEGIN
    IF :NEW.Record_ID IS NULL THEN
        SELECT ltr_seq.NEXTVAL INTO :NEW.Record_ID FROM DUAL;
    END IF;
END;
/

CREATE SEQUENCE rm_seq START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER trg_rm_id
BEFORE INSERT ON ROOM
FOR EACH ROW
BEGIN
    IF :NEW.Room_ID IS NULL THEN
        SELECT rm_seq.NEXTVAL INTO :NEW.Room_ID FROM DUAL;
    END IF;
END;
/

CREATE SEQUENCE bed_seq START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER trg_bed_id
BEFORE INSERT ON BED
FOR EACH ROW
BEGIN
    IF :NEW.Bed_ID IS NULL THEN
        SELECT bed_seq.NEXTVAL INTO :NEW.Bed_ID FROM DUAL;
    END IF;
END;
/

CREATE SEQUENCE adm_seq START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER trg_adm_id
BEFORE INSERT ON ADMISSION
FOR EACH ROW
BEGIN
    IF :NEW.Admission_ID IS NULL THEN
        SELECT adm_seq.NEXTVAL INTO :NEW.Admission_ID FROM DUAL;
    END IF;
END;
/

CREATE SEQUENCE emq_seq START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER trg_emq_id
BEFORE INSERT ON EMERGENCY_QUEUE
FOR EACH ROW
BEGIN
    IF :NEW.Queue_ID IS NULL THEN
        SELECT emq_seq.NEXTVAL INTO :NEW.Queue_ID FROM DUAL;
    END IF;
END;
/

CREATE SEQUENCE med_seq START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER trg_med_id
BEFORE INSERT ON MEDICINE_STORE
FOR EACH ROW
BEGIN
    IF :NEW.Medicine_ID IS NULL THEN
        SELECT med_seq.NEXTVAL INTO :NEW.Medicine_ID FROM DUAL;
    END IF;
END;
/

CREATE SEQUENCE bil_seq START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER trg_bil_id
BEFORE INSERT ON BILL
FOR EACH ROW
BEGIN
    IF :NEW.Bill_ID IS NULL THEN
        SELECT bil_seq.NEXTVAL INTO :NEW.Bill_ID FROM DUAL;
    END IF;
END;
/

CREATE SEQUENCE pay_seq START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER trg_pay_id
BEFORE INSERT ON PAYMENT
FOR EACH ROW
BEGIN
    IF :NEW.Payment_ID IS NULL THEN
        SELECT pay_seq.NEXTVAL INTO :NEW.Payment_ID FROM DUAL;
    END IF;
END;
/
